version: "3.9"

services:
  judgehost:
    image: domjudge/judgehost:9.0.0
    container_name: judgehost
    hostname: judgehost

    privileged: true
    cgroupns: host
    restart: always

    environment:
      DAEMON_ID: 0
      JUDGEDAEMON_PASSWORD: domjudgeisas
      DOMSERVER_BASEURL: http://192.168.17.108
      CONTAINER_TIMEZONE: Asia/Bangkok

    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
